[package]
name = "nscldaq_ringmaster"
version = "0.1.0"
edition = "2018"
authors = "Ron FOx"
license = "GPL-3.0"
description = "RUST replacement for NSCLDAQ RingMaster - only requires ring2stdout"
homepage = "http://docs.frib.ms.edu/daq"
repository = "https://gitlab.msu.edu/foxr/rust-ringmaster.git"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nscldaq_ringbuffer = "0.6.0"
clap = "^2.27.1"
simple-logging = "2.0.2"
sysinfo = "0.25.2"
log = "0.4"
whoami="1.2.1"
portman_client="0.1.0"
