name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --lib
    - name: Build for a release
      if: ${{ startsWith(github.ref, 'refs/tags') }}
      run: cargo build --release
    - name: Create a release
      if: ${{ startsWith(github.ref, 'refs/tags') }}
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: target/release/nscldaq_ringmster
        name: Release of ${{ github.ref_name }}
